name: Build

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    name: Build image and push onto dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true
      - name: Build project
        run: pnpm build
      - name: ls
        run: ls -al
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
#   tag:
#     name: Add tags to repository
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - id: version
#         uses: wdzeng/version@v1
#         with:
#           prefix: v
#       - name: Add tags
#         run: |
#           git tag -f ${{ steps.version.outputs.version }} main && \
#           git push -f origin ${{ steps.version.outputs.version }}
